- hosts: all
  connection: local
  become: yes
  tasks:
    - name: Install Apache server
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
        cache_valid_time: 3600


#  ansible-playbook -c local -i localhost, apt_apache.yaml