---
- hosts: all
  become: yes
  vars:
    users:
      - postgres
      - todo
  tasks:
  - name: add users
    ansible.builtin.user:
      name: "{{ item }}"
      state: present
    loop: "{{ users }}"