- hosts: all
  become: yes
  tasks:
    - name: pre requasites
      ansible.builtin.apt:
        name:
        - apt-transport-https
        - python3-pip
        update_cache: yes
    - name: docker gpg key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: docker repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present
        filename: docker
    - name: install docker
      ansible.builtin.apt:
        name: docker-ce
        update_cache: yes
    - name: install docker python package
      ansible.builtin.pip:
        name: docker

- hosts: dbservers
  become: yes
  tasks: 
    - name: start database
      community.docker.docker_container:
        name: todo
        image: postgres:14
        restart_policy: always
        ports: 
        - "5432:5432"
        env:
          POSTGRES_USER: todo
          POSTGRES_PASSWORD: todo
- hosts: webservers
  become: yes
  tasks:
    - name: start application
      community.docker.docker_container:
        name: todo
        image: "registry.gitlab.com/learning-ansible/todo:stable"
        restart_policy: always
        ports:
        - "80:5000"
        env:
          DATABASE_URL: "postgres://todo:todo@<ip of database>/todo"


