- hosts: all
  become: yes
  tasks:
    - name: pre requasites
      ansible.builtin.apt:
        name:
        - apt-transport-https
        - python3-pip
        update_cache: yes
    - name: docker gpg key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: docker repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present
        filename: docker
    - name: install docker
      ansible.builtin.apt:
        name: docker-ce
        update_cache: yes
    - name: install docker python package
      ansible.builtin.pip:
        name: docker
    - name: start container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ container_image }}"
        restart_policy: always
        ports: "{{ container_ports }}""
        env: "{{ container_env }}"